# Generated by Django 4.0.4 on 2023-03-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_receipt_delete_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
