# Generated by Django 4.0.4 on 2023-03-03 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_retailer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retailer',
            old_name='id',
            new_name='vat',
        ),
    ]
